
function descriptor = descriptorWindau(subsequence)
    % note: if the acceleration is in gravity-direction, remember to
    % subtract 9.81 before doing feature computation
     
    statfeatureLists = struct('mean',      true, ...
                               'std',       true, ...
                               'rms',       true, ...
                               'meanderivative',    true, ...
                               'meancrossingrate',  true);

    statfield2function = struct('mean',             'meanSeq', ...
                                'std',              'stdSeq', ...
                                'rms',              'rmsSeq', ...
                                'meanderivative',   'meanDerivative', ...
                                'meancrossingrate', 'meancrossingRate');

    physfeatureLists = struct('meanMI', true, ...
                              'stdMI', true, ...
                              'NSM', true, ...
                              'accelEnergy', false, ...
                              'corrcoef', true);

    physfield2function = struct('meanMI', 'meanMotionIntensity', ...
                                'stdMI', 'stdMotionIntensity', ...
                                'NSM', 'NSM', ...
                                'accelEnergy', 'accelEnergy', ...
                                'corrcoef', 'corrcoefSeq');
% 
%    if bGravityDirection == true
%        subsequence = subsequence - 9.81;
%    end

   [descriptor, ~, ~]  =  ...
                    featureExtractor(subsequence(:), ...
                        statfeatureLists, statfield2function, ...
                          physfeatureLists, physfield2function);


                      
end