function datasets = getDatasetNamesUCRold    

    datasets = {
        
    '50words'
    'Adiac'
    'Beef'
    'Car'
    'CBF'
    'ChlorineConcentration'
    'CinC_ECG_torso'
    'Coffee'
    'Cricket_X'
    'Cricket_Y'
    'Cricket_Z'
    'DiatomSizeReduction'
    'ECG200'
    'ECGFiveDays'
    'FaceAll'
    'FaceFour'
    'FacesUCR'
    'FISH'
    'Gun_Point'
    'Haptics'
    'InlineSkate'
    'ItalyPowerDemand'
    'Lighting2'
    'Lighting7'
    'MALLAT'
    'MedicalImages'
    'MoteStrain'
    'NonInvasiveFatalECG_Thorax1'
    'NonInvasiveFatalECG_Thorax2'
    'OliveOil'
    'OSULeaf'
    'Plane'
    'SonyAIBORobotSurface'
    'SonyAIBORobotSurfaceII'
    'StarLightCurves'
    'SwedishLeaf'
    'Symbols'
    'synthetic_control'
    'Trace'
    'TwoLeadECG'
    'Two_Patterns'
    'uWaveGestureLibrary_X'
    'uWaveGestureLibrary_Y'
    'uWaveGestureLibrary_Z'
    'wafer'
    'WordsSynonyms'
    'yoga'
        };
 
end